$timesToRun = @('12:00am',
                '01:00am',
               '10:00pm',
                '11:00pm'
               )
$path = 'C:\IPAddressMailer'
$script = "$path\IPAddressMailer.ps1"
$action = New-ScheduledTaskAction -Execute 'Powershell.exe' `
  -Argument "-NoProfile -WindowStyle Hidden -File `"$script`""
  
foreach ($timeToRun in $timesToRun)
{
  $taskName = "SendExternalIP_at_$($timeToRun -replace ':', '_')"

  $trigger = New-ScheduledTaskTrigger -Daily -at $timeToRun
    $description = @"
At $timeToRun daily E-Mail the External IP Address using the PowerShell script $script
 These tasks generated by the IPAddressMailer scripts written by Robert C. Cain, @ArcaneCode.
 
"@
  $settings = New-ScheduledTaskSettingsSet -Hidden -AllowStartIfOnBatteries -WakeToRun
   $prin = New-ScheduledTaskPrincipal -UserId "NT AUTHORITY\SYSTEM" `
                                     -LogonType ServiceAccount `
                                     -RunLevel Highest
  
  Write-Host "Creating task $taskName" -ForegroundColor Yellow
  Register-ScheduledTask -Action $action `
                         -Trigger $trigger `
                         -TaskName $taskName `
                         -Description $description `
                         -Settings $settings `
                         -Principal $prin `
                         -Force | Out-Null

}

Write-Host 'Here are the list of created tasks.' -ForegroundColor Green
Get-ScheduledTask -TaskPath '\' -TaskName 'SendExternalIP_at*'
